apiVersion: compliance.openshift.io/v1alpha1
kind: CustomRule
metadata:
  name: kubevirt-nonroot-feature-gate-is-enabled
  namespace: openshift-compliance
spec:
  title: "KubeVirt nonRoot Feature Gate Must Be Enabled"
  id: kubevirt_nonroot_feature_gate_is_enabled
  description: "Unauthorized access to a root account without restrictions implemented by the nonRoot feature introduces the risk of unintended or unauthorized access to privilege elevation and the ability to perform administrative tasks."
  failureReason: "The '.spec.featureGates.nonRoot' field is missing or not set to 'true' in the 'kubevirt-hyperconverged' resource."
  severity: Medium
  checkType: Platform
  scannerType: CEL
  inputs:
    - name: hcoList
      kubernetesInputSpec:
        apiVersion: hco.kubevirt.io/v1beta1
        resource: hyperconvergeds
  expression: |
    hcoList.items.filter(h,
        h.metadata.name == 'kubevirt-hyperconverged' &&
        h.metadata.namespace == 'openshift-cnv'
    ).size() == 1 &&
    hcoList.items.filter(h,
        h.metadata.name == 'kubevirt-hyperconverged' &&
        h.metadata.namespace == 'openshift-cnv'
    ).all(h,
        has(h.spec.featureGates) &&
        has(h.spec.featureGates.nonRoot) &&
        h.spec.featureGates.nonRoot == true
    )
